function bootParams = specBootAvgParams( generalParams )

i = 1;
%Start of trial
bootParams(i).trigger = "start";
bootParams(i).subtractBaseline = false;
bootParams(i).trialSpec = {...
    ["forward"],...
    ["left"],...
    ["right"],...
};
i = i+1;

%Cue responses
%Do cue responses or selectivity differ on correct vs. error trials?
%Contralateral Towers vs. Puffs??
%Tactile vs. Visual Rule?
bootParams(i).trigger = "towers";
bootParams(i).subtractBaseline = true;
bootParams(i).trialSpec = {...
    ["leftTowers"],...
    ["rightTowers"],...
    ["hiTowers"],...
    ["loTowers"],...
    ["leftTowers","hiTowers"],...
    ["leftTowers","loTowers"],...
    ["rightTowers","hiTowers"],...
    ["rightTowers","loTowers"]...
    };
i = i+1;

%Left and right cues aligned to cue onsets
bootParams(i).trigger = "puffs";
bootParams(i).subtractBaseline = true;
bootParams(i).trialSpec = {...
    ["leftPuffs"],...
    ["rightPuffs"],...
    ["hiPuffs"],...
    ["loPuffs"],...
    ["leftPuffs","hiPuffs"],...
    ["leftPuffs","loPuffs"],...
    ["rightPuffs","hiPuffs"],...
    ["rightPuffs","loPuffs"]...
    };
i = i+1;

%All trials aligned to turnEntry
bootParams(i).trigger = "turnEntry";
bootParams(i).subtractBaseline = true;
bootParams(i).trialSpec = {...
    "forward",...
    "left",...
    "right",...
    };
i = i+1;

%Aligned to y-position, no baseline subtraction
bootParams(i).trigger = "cueRegion";
bootParams(i).subtractBaseline = false;
bootParams(i).trialSpec = {...
    ["forward"],...
    ["leftPuffs"],...
    ["rightPuffs"],...
    ["hiPuffs"],...
    ["leftPuffs","hiPuffs"],...
    ["rightPuffs","hiPuffs"],...
    ["loPuffs"],...
    ["leftPuffs","loPuffs"],...
    ["rightPuffs","loPuffs"],...
    ["noPuffs"],...
    ["leftTowers"],...
    ["rightTowers"],...
    ["hiTowers"],...
    ["hiTowers","leftTowers"],...
    ["hiTowers","rightTowers"],...
    ["loTowers"],...
    ["loTowers","leftTowers"],...
    ["loTowers","rightTowers"],...
    ["noTowers"],...
    ["left"],...
    ["right"],...
    ["left","correct"],...
    ["right","correct"],...
    ["correct"],... %"Accuracy"
    ["correct","hiTowers"],...
    ["correct","loTowers"],...
    ["correct","noTowers"],...
    ["correct","hiPuffs"],...
    ["correct","loPuffs"],...
    ["correct","noPuffs"],...
    ["error"],...
    ["error","hiTowers"],...
    ["error","loTowers"],...
    ["error","noTowers"],...
    ["error","hiPuffs"],...
    ["error","loPuffs"],...
    ["error","noPuffs"],...
    ["priorCorrect"],... %Reward history
    ["priorError"],...
    ["priorLeft"],...
    ["priorRight"],...
    ["congruent","left"],...
    ["conflict","left"],...
    ["congruent","right"],...
    ["conflict","right"],...
    ["congruent","correct"],...
    ["congruent","error"],...
    ["conflict","correct"],...
    ["conflict","error"],...
    ["conflict"]};
i = i+1;

%Aligned to outcome
bootParams(i).trigger = "outcome";
bootParams(i).subtractBaseline = true;
bootParams(i).trialSpec = {...
    ["correct"],...
    ["error"],...
    ["priorCorrect","correct"],...
    ["priorError","correct"],...
    ["priorCorrect","error"],...
    ["priorError","error"],...
    ["left","correct"],...
    ["right","correct"],...
    ["left","error"],...
    ["right","error"],...
    ["noPuffs","correct"],...
    ["noPuffs","error"],...
    ["noTowers","correct"],...
    ["noTowers","error"],...
    ["hiPuffs","correct"],...
    ["loPuffs","correct"],...
    ["hiPuffs","error"],...
    ["loPuffs","error"],...
    ["hiTowers","correct"],...
    ["loTowers","correct"],...
    ["hiTowers","error"],...
    ["loTowers","error"],...
    ["congruent"],...
    ["conflict"]};
i = i+1;

%Left and right cues aligned to first cue onset
bootParams(i).trigger = "firstPuff";
bootParams(i).subtractBaseline = true;
bootParams(i).trialSpec = {...
    ["leftPuffs"],...
    ["rightPuffs"],...
    ["hiPuffs"],...
    ["loPuffs"],...
    ["leftPuffs","hiPuffs"],...
    ["leftPuffs","loPuffs"],...
    ["rightPuffs","hiPuffs"],...
    ["rightPuffs","loPuffs"]};
i = i+1;

bootParams(i).trigger = "firstTower";
bootParams(i).subtractBaseline = true;
bootParams(i).trialSpec = {...
    ["leftTowers"],...
    ["rightTowers"],...
    ["hiTowers"],...
    ["loTowers"],...
    ["leftTowers","hiTowers"],...
    ["leftTowers","loTowers"],...
    ["rightTowers","hiTowers"],...
    ["rightTowers","loTowers"]};
i = i+1;

%Left and right cues aligned to first cue onset
bootParams(i).trigger = "lastPuff";
bootParams(i).subtractBaseline = true;
bootParams(i).trialSpec = {...
    ["leftPuffs"],...
    ["rightPuffs"],...
    ["leftPuffs","left"],...
    ["leftPuffs","right"],...
    ["rightPuffs","right"],...
    ["rightPuffs","left"]};
i = i+1;

bootParams(i).trigger = "lastTower";
bootParams(i).subtractBaseline = true;
bootParams(i).trialSpec = {...
    ["leftTowers"],...
    ["rightTowers"],...
    ["leftTowers","left"],...
    ["leftTowers","right"],...
    ["rightTowers","right"],...
    ["rightTowers","left"]};
i = i+1;



%Append general params
fields = string(fieldnames(generalParams)); %Some params specified in params_...m may overwrite bootParams(i)
for j = 1:numel(fields)
    if fields(j)=='subtractBaseline' && ~generalParams.subtractBaseline
        continue
    end
    [bootParams(1:numel(bootParams)).(fields{j})] = deal(generalParams.(fields{j}));
end

