function params = specEncodingParams(params)

%Predictors for full/partial models

switch params.modelName

    case 'FM'
        %Basic "Full Model"
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "leftPuffs_position","rightPuffs_position","leftTowers_position","rightTowers_position",...
            "reward","noReward",...
            "viewAngle","velocity","acceleration","ITI"];
        params.initFcn_position = @ones; %ITI position: @ones for last final position, @nan to neglect ITI


    case 'cuesPosITI'
        params.predictorNames = [
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs_position","rightPuffs_position","leftTowers_position","rightTowers_position",...
            "ITI",...
            ];
        params.initFcn_position = @ones; %ITI positi

    case 'firstCuesPosRew'
        params.predictorNames = [
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs_position","rightPuffs_position","leftTowers_position","rightTowers_position",...
            "reward","noReward",...
            ];
        params.initFcn_position = @ones; %ITI positi

    case 'only_cues'
        params.predictorNames = [...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            ];
        params.initFcn_position = @ones; %ITI position: @ones for last final position, @nan to neglect ITI
    
    case 'only_allCues'
        params.predictorNames = [...
            "leftPuffs","rightPuffs","leftTowers","rightTowers"...
            ];
        params.initFcn_position = @ones; %ITI position: @ones for last final position, @nan to neglect ITI

    case 'only_firstCues'
        params.predictorNames = [
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower"...
            ];
        params.initFcn_position = @ones; %ITI position: @ones for last final position, @nan to neglect ITI

    case 'only_posXcueType'
        params.predictorNames = [...
            "leftPuffs_position","rightPuffs_position","leftTowers_position","rightTowers_position"...
            ];
        params.initFcn_position = @ones; %ITI positi

    case 'firstCues_posXcueType'
        params.predictorNames = [
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs_position","rightPuffs_position","leftTowers_position","rightTowers_position",...
            ];
        params.initFcn_position = @ones; %ITI positi

    case 'FM_trialIdx'
        %FM plus trialIdx
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "reward","noReward",...
            "trialIdx","position","viewAngle","velocity","acceleration"];
        params.initFcn_position = @ones;

    case 'FM_time'
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "reward","noReward",...
            "time","viewAngle","velocity","acceleration"];
        params.initFcn_position = @ones;

    case 'FM_firstCueOnly'
        %FM with NaN position during ITI
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "reward","noReward",...
            "position","viewAngle","velocity","acceleration"];
        params.initFcn_position = @ones;

end

%List variables by type
pNames = params.predictorNames;
varNames.eventVars = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "reward","noReward"];
varNames.positionVars = ["position",...
    "leftPuffs_position","rightPuffs_position",...
    "leftTowers_position","rightTowers_position"];
varNames.indicatorVars = ["ITI","trialIdx","accuracy","priorOutcome"];
varNames.kinematicVars = ["viewAngle","velocity","acceleration"];
for f = string(fieldnames(varNames))'
    params.(f) = pNames(ismember(pNames,varNames.(f)));
end

