function params = specEncodingParams(params)

%Predictors for full/partial models

switch params.modelName

    case 'FM'
        %Basic "Full Model"
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "leftPuffs_position","rightPuffs_position","leftTowers_position","rightTowers_position",...
            "reward","noReward",...
            "viewAngle","velocity","acceleration","ITI"];
        params.initFcn_position = @ones; %ITI position: @ones for last final position, @nan to neglect ITI

    case 'Pos_rew'
        %Position + Reward model
        params.predictorNames = ["reward","noReward",...
            "position","ITI","viewAngle","velocity","acceleration"];
        params.initFcn_position = @ones; %ITI position: @ones for last final position, @nan to neglect ITI

    case 'Pos_rew_cues'
        params.predictorNames = ["firstLeftPuff","firstRightPuff",...
            "firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "reward","noReward",...
            "position","ITI"];
        params.initFcn_position = @ones; %ITI position: @ones for last final position, @nan to neglect ITI

    case 'FM_trialIdx'
        %FM plus trialIdx
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "reward","noReward",...
            "trialIdx","position","viewAngle","velocity","acceleration"];
        params.initFcn_position = @ones;

    case 'FM_time'
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "reward","noReward",...
            "time","viewAngle","velocity","acceleration"];
        params.initFcn_position = @ones;

    case 'FM_firstCueOnly'
        %FM with NaN position during ITI
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "reward","noReward",...
            "position","viewAngle","velocity","acceleration"];
        params.initFcn_position = @ones;

    case 'FM_posNAN'
        %FM with NaN position during ITI
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "reward","noReward",...
            "position","viewAngle","velocity","acceleration"];
        params.initFcn_position = @nan;

    case 'No_Outcome'
        %FM with NaN position during ITI
        params.predictorNames = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "position","viewAngle","velocity","acceleration"];
        params.initFcn_position = @nan;

end

%List variables by type
pNames = params.predictorNames;
varNames.eventVars = ["start",...
            "firstLeftPuff","firstRightPuff","firstLeftTower","firstRightTower",...
            "leftPuffs","rightPuffs","leftTowers","rightTowers",...
            "reward","noReward"];
varNames.positionVars = ["position",...
    "leftPuffs_position","rightPuffs_position",...
    "leftTowers_position","rightTowers_position"];
varNames.indicatorVars = ["ITI","trialIdx","accuracy","priorOutcome"];
varNames.kinematicVars = ["viewAngle","velocity","acceleration"];
for f = string(fieldnames(varNames))'
    params.(f) = pNames(ismember(pNames,varNames.(f)));
end

