function population = summarize_popBySession( sessions )      

%Matrix of p-values (nCells x nSessions) 
allSessionDates = [sessions.session_date];
allCellIDs = string(unique(cat(1,sessions.cellID))); %cell IDs from all sessions
for f = string(fieldnames([sessions.pValues]))'
     pValues.(f) = NaN(numel(allCellIDs), numel(allSessionDates)); %initialize
     for dateIdx = 1:numel(allSessionDates)
         cellIdx = ismember(allCellIDs, sessions(dateIdx).cellID); %cell IDs present in session(i)
         pValues.(f)(cellIdx, dateIdx) =  sessions(dateIdx).pValues.(f);
     end
end
N = sum(~isnan(pValues.(f)),1);

%Population summary structure
population = struct(...
    'sessionDates', allSessionDates,...
    'cellIDs', allCellIDs,...
    'pValues', pValues,...
    'pSignificant', [sessions.pSignificant],...
    'N', N,...
    'alpha', sessions(1).alpha...
    );